import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

export async function GET(_req: NextRequest) {
  // Recent approvals (approve/reject events)
  const recentApprovals = await prisma.approval.findMany({
    take: 10,
    orderBy: { createdAt: "desc" },
    include: {
      user: true,
      artifact: { include: { project: true } },
    },
  });

  // Recent artifacts generated
  const recentArtifacts = await prisma.artifact.findMany({
    take: 10,
    orderBy: { createdAt: "desc" },
    include: { project: true, owner: true },
  });

  // Recent projects created
  const recentProjects = await prisma.project.findMany({
    take: 5,
    orderBy: { createdAt: "desc" },
  });

  // Merge and sort by date
  type ActivityItem = {
    id: string;
    type: "approval" | "artifact" | "project";
    title: string;
    description: string;
    projectName: string;
    projectId: string;
    status?: string;
    createdAt: string;
  };

  const activities: ActivityItem[] = [
    ...recentApprovals.map((a: (typeof recentApprovals)[number]) => ({
      id: `approval-${a.id}`,
      type: "approval" as const,
      title: a.artifact.title,
      description: `${a.status === "approved" ? "Approved" : "Rejected"} by ${a.user.name}`,
      projectName: a.artifact.project.name,
      projectId: a.artifact.project.id,
      status: a.status,
      createdAt: a.createdAt.toISOString(),
    })),
    ...recentArtifacts.map((a: (typeof recentArtifacts)[number]) => ({
      id: `artifact-${a.id}`,
      type: "artifact" as const,
      title: a.title,
      description: `Generated by ${a.owner?.name ?? "AI"}`,
      projectName: a.project.name,
      projectId: a.project.id,
      status: a.status,
      createdAt: a.createdAt.toISOString(),
    })),
    ...recentProjects.map((p: (typeof recentProjects)[number]) => ({
      id: `project-${p.id}`,
      type: "project" as const,
      title: p.name,
      description: "Project created",
      projectName: p.name,
      projectId: p.id,
      createdAt: p.createdAt.toISOString(),
    })),
  ];

  activities.sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  );

  return NextResponse.json({ activities: activities.slice(0, 15) });
}
